name: mofex
channels:
  - plotly
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.*
  - numpy
  - opencv=4.2.*
  - plotly=4.7.*
  - psutil=5.7.*
  - plotly-orca=1.3.*
  - chart-studio=1.1.*
  - click=7.1.*
  - pip
  - pip:
      - keyboard
      - inquirer=2.6.*
